### ISSUE TITLE
Comments. 

### ISSUE THREAD

**Issue by rjrobinson** [facebookgo/generics#1]
wow...

**Comment by tywkeene** [comment]
Usually I'd ignore this kind of thing but I'm curious what the point of this is.

**Comment by rjrobinson** [comment]
getting rick rolled... of course.

**Comment by akashnimare** [comment]
How do I make this kind of gifs from a video?

**Comment by imranity** [comment]
@akashnimare  http://makeagif.com/youtube-to-gif :smile_cat:
